language: node_js
node_js:
- '7'
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: VcIlJe7ACnrbaMdygQospIsTBiAr371VkGYa6KkbgWPsWibeaCVX50Eprui0En+l4ZwQgf+nADc0hcx/gdyRhvRbicG/uf1hpQIVBRhq8JkWo288uFv0ljcQBz1KWcBmk1Ipxn7ZjcwLSykTknzBov9ajVBEqTX2hcjP94OixMvJx9qWZmM/5mZK0Jbm9ongWHB8r4N3AxX7b4JWw4wmcmn4Rrtn2mouqxGSONHsOeX3fTee46sZD2mxPsJl9nwkn8OQ8uUXH2gHyx56bmcQcxiIhrsp3ZkXZYxDwdLwgsprEswe8OtlrjAgOLcAqEXTriE7sJ0vWR34sF9S0pDWV0MVAuJ42myfCZyvc9vXGZ2sQVbih4d55EeVJchleRjgB9GF/qWceHDvv4j7EiJSQ+1XIHb54mdmHkvavVRSVKo9HaDs+k/RLBb6Fch+Y0l/L1SQXsra0c5dUtkD01WagX43m+KMlI/ayLmmx8khcD9UVEfTbnz0fWzbCFklS15T4D2qOVm3JAiNxTdbfClKK2dOtaqxr0aw985Z3AHqkqKTiSxuyfcrWK24CcUhgBrMuZw0naD7Zl5wENpsGnCikSedPJ9Qb2I+TIWnWpToKTM6M+QeoOAV6ZLMcmisPv3SRl7S+YwtsW3jveoer0BrneXgzNCoray8qgRq5enKKkQ=
