language: node_js
node_js:
- '7'
script:
- npm test
deploy:
  api_key:
    secure: hUpg1IwDbl5ZTef0jfcbSQ2GickbKMn95Mn/gsQ/39lvCTXON5bm1CN6X3TNHjaCqfD3sawzLP1PvQq3f8d4HbdsOINWncpmctO7MHD59QXkydfviPmhNLKt+gnbjEh9tOLPv1P5UB5vkcA2jqh7wUdQRs8BoSwE62x+8QvbbC3YCx6qQfXP4d7otKyDWuYQb22FzNVvm38GQLHj7aH3SmxS6pBChS0QI6qi8VrT9nhObNzVp8fqannsRQQdPDD3G3qi4I0upc49UKM3Weesf8zDCco9A06Hqe2tvwF6ydlbi+eqwazmYzjYo/S/wl7XW3J+xKNm30P1xuqWV3YX2zC8KpNn24rQ9pYUFDpnLQoW6Ah3gXpxpNZozo7lf80Jo9W8hO9T1mWAsQ37vRQeI7tyP+8QsTM4yEbbIrjkL54GL5ToYrki3qXG9SkVxzQE+NalniHbP5JOa2IIIJvlJ31NrX9fCrQlkj4yv0MFlBdQhp5gz6QtEb2jwkNLbJNLZVCM3TyTv6JVtoZAxMwxR8Ir10j3OoI2cABd4ij2FTOWS+og/rzUBey+0XcMPgmKjkoM1yZXvc2aR3U10gVweG2T8+sHyPJvMyx4TmCDXS2FNqoSRH/zY7N7937gOgHH1EO+nkKcAF9Sf/bR5f0JRJm7XgthxiqAswtVdAqa5cI=
